# Generated by Django 5.0.1 on 2024-02-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_supplies_delete_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplies',
            old_name='filename',
            new_name='image',
        ),
    ]
